<?php
return array (
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '907',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '0',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '0',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '904',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '0',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '903',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '0',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'kuyun' => 
  array (
    'status' => '1',
    'from' => 'kuyun',
    'show' => 'OK播放器',
    'des' => 'http://okzyw.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '2',
    'tip' => '来源：OK资源',
    'id' => 'kuyun',
  ),
  'ckm3u8' => 
  array (
    'status' => '1',
    'from' => 'ckm3u8',
    'show' => 'ckm3u8',
    'des' => 'http://okzyw.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => '//www.dplayer.tv/?url=',
    'sort' => '1',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'ckm3u8',
  ),
);